#ifndef HDEFINE_H
#define HDEFINE_H

// Tile
#define TILE_COUNT 8

// Timer
#define LIFE_MAX_TIME 5000
#define LIFE_ADD_INTERVAL_INIT 1000
#define LIFE_ADD_INTERVAL_REDUCE_SIZE 10
#define LIFE_ADD_INTERVAL_MIN 150
#define LIFE_REDUCE_INTERVAL 1000

#define CANCEL_COMBO_INTERVAL 1500
#define FEVER_INTERVAL 5000

// Score
#define DEFAULT_SCORE 100
#define FEVER_SCORE DEFAULT_SCORE * 2


#define COMBO_FOR_FEVER 30

// WINDOW OS
#define DESKTOP_OS_WIDTH 300
#define DESKTOP_OS_HEIGHT 600

#endif // HDEFINE_H
